language: cpp
sudo: false

matrix:
  include:

    - compiler: gcc
      addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libgccjit-6-dev']
      env: COMPILER=g++-5
    
    - compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libgccjit-6-dev']
      env: COMPILER=g++-6
    
    - compiler: clang
      addons: &clang36
        apt:
          sources: ['llvm-toolchain-precise-3.6', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.6', 'libgccjit-6-dev']
      env: COMPILER=clang++-3.6
    
    - compiler: clang
      addons: &clang37
        apt:
          sources: ['llvm-toolchain-precise-3.7', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.7', 'libgccjit-6-dev']
      env: COMPILER=clang++-3.7
    
    - compiler: clang
      addons: &clang38
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.8', 'libgccjit-6-dev']
      env: COMPILER=clang++-3.8

    - compiler: clang
      addons: &clang39
        apt:
          sources: ['llvm-toolchain-precise-3.9', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.9', 'libgccjit-6-dev']
      env: COMPILER=clang++-3.9

branches:
    only:
        - /.*/

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
    - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - https://cmake.org/files/v3.8/cmake-3.8.0-rc4-Linux-x86_64.tar.gz | tar --strip-components=1 -xz -C cmake
    - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
    - export CXX=${COMPILER}
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/gcc/x86_64-linux-gnu/6
    - export LIBRARY_PATH=${LIBRARY_PATH}:/usr/lib/gcc/x86_64-linux-gnu/6
    - export PATH=${PATH}:/usr/lib/gcc/x86_64-linux-gnu/6:/usr/lib/gcc/x86_64-linux-gnu/6/include
    - cmake ..;
    
script:
    - make -j 2

after_success:
      ./basics;
      ./labels;
      ./square_root;